language: node_js
node_js: 6
install:
  - npm install
script:
  - npm run build
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    repo: mvc-spec/www.mvc-spec.org
    branch: master
env:
  global:
    secure: ig67usznFCh3xFyvPyr3pjKjzQZxoTjIrdKd0OazcvLJk8eydPliUhgchH9yIcZJ+l6CP//1xqCBVbgeFe8Y23bpaIj+c257D24V8eAn6VXlX6GIphOZ7cMaimCMcFGi4S0LJj2GOjPKGkrPAWaq3ve4NsigSIuXfTnkKBV0GYzEZS+kmTbaworkOW0qQPSw+LvxnJcRli9tZXMwC2tIE3YvBXAu7edLuNr77vzvfxnsLBABZuy2qGP4/ZC/+QiwXHiZ3Be8VEBIlAo/5/As/Da463EAOetYK1yvvhrSzb5BD4Csx6g2xmjMTHqhmB+fs/9vaU3tb/72Yll4y+o3p8gDD4ehKG4NyDExEtBM2xZONBprSb+S7tXSZ+5BPLpDTjqNKYUCorLeCd+vcAluf/w529A9TnX44l2+y0ddrzNZDqsKVBH5FPWMGhrQIGTL3bOLTRKtJNrPzygpstSTyrZyo+SwP2AYIzCG0PN+Dp3DQZLGEbgj5jF/pF2q6b1OQm9IDqAJgrILZKRsqg9wX8FNUYpOkUHIux2cZycAxXjZXwuxaWBHt35jUePEq/eQHKUuJ37SIJllcWHKCVdlzUlX24tj5adUUkeb9st9lqmCtLNSCaKie9DA3NOWLhltJ0VVPGKOPqoO5A+pcDwh14clFq8jaums+85IfykcYoA=
